const elHands = document.querySelectorAll('.hand-js');
const elUser = document.querySelector('#user');
const elRobot = document.querySelector('#robot');
const elRefershGame = document.querySelector('#refreshGame');
const elGameZone = document.querySelector('#gameZone');
const elResultZone = document.querySelector('#resultZone');
let elTextName = document.querySelector("#textname");
const elModeChanger = document.querySelector('#modeChanger');
let elAdvancedMode = document.getElementById("advancedMode");
export {elHands, elUser, elRobot, elRefershGame, elGameZone, elResultZone, elTextName,elModeChanger,elAdvancedMode};